project_id = "efifbuqctylsujiauabg"

[auth]
enable_signup = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = false

[auth.sms]
enable_signup = false

[functions.dokohilf-editor]
verify_jwt = true

[functions.dokohilf-tts]
verify_jwt = true

[functions.dokohilf-guide-audio-build]
verify_jwt = true

[functions.dokohilf-guide-audio]
verify_jwt = true

[functions.dokohilf-chat-router]
verify_jwt = false
