project_id = "efifbuqctylsujiauabg"

[functions.dokohilf-editor]
verify_jwt = true

[functions.dokohilf-tts]
verify_jwt = true

[functions.dokohilf-guide-audio-build]
verify_jwt = true

[functions.dokohilf-guide-audio]
verify_jwt = true
