import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
await import('../assets/guide-progress.js');
const { formatProgress } = globalThis.DokoHilfGuideProgress;
const script = await readFile(new URL('../assets/guide-progress.js', import.meta.url), 'utf8');
const edgeFunction = await readFile(new URL('../supabase/functions/dokohilf-guide-state/index.ts', import.meta.url), 'utf8');
test('Schrittanzeige wird verständlich formatiert', () => { assert.equal(formatProgress(1, 7), 'Schritt 1 von 7'); assert.equal(formatProgress(4, 7), 'Schritt 4 von 7'); assert.equal(formatProgress(0, 0), 'Schritt 1 von 1'); });
test('Guide-Leiste besitzt die kompakte Aufgabensteuerung', () => { assert.match(script, />Zurück</); assert.match(script, />Neu starten</); assert.match(script, />Ablauf wechseln</); assert.match(script, /currentGuide/); assert.match(script, /commandRow/); });
test('Fortschritt aus der Routerantwort wird ohne erneutes Erraten übernommen', () => { assert.match(script, /payloadHasProgress/); assert.match(script, /renderGuide\(payload\)/); assert.match(script, /guideStepCount/); assert.match(script, /guideStep/); });
test('Fortschritts-Endpunkt bleibt als kompatibler Metadaten-Fallback erhalten', () => { assert.match(script, /dokohilf-guide-state/); assert.match(edgeFunction, /guideStepCount/); assert.match(edgeFunction, /guideStep/); assert.match(edgeFunction, /guideTitle/); assert.doesNotMatch(edgeFunction, /steps:\s*guide\.steps/); });
