-- HISTORISCHER MIGRATIONSSTAND: Dieser nie produktiv genutzte Account-/Editorpfad
-- wird durch 20260807230003_remove_app_account_infrastructure.sql dauerhaft entfernt.
-- Die folgenden Befehle dokumentieren nur die bereits angewendete Reihenfolge und
-- sind keine aktuelle oder spätere Produktplanung.
-- DokoHilf Block 7: geschützte Redaktion ohne öffentliche Selbstregistrierung.
-- Enthält ausschließlich Struktur und Berechtigungen, keine Nutzer- oder Echtdaten.

create table if not exists public.dokohilf_user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('staff', 'editor', 'admin')),
  active boolean not null default true,
  assigned_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.dokohilf_user_roles is
  'Kontrolliert zugewiesene DokoHilf-Rollen. Keine automatische Rollenzuweisung bei Registrierung.';

alter table public.dokohilf_guides
  add column if not exists review_interval_days integer not null default 180,
  add column if not exists review_due_at timestamptz,
  add column if not exists reviewed_by uuid references auth.users(id) on delete set null,
  add column if not exists approved_at timestamptz,
  add column if not exists approved_by uuid references auth.users(id) on delete set null,
  add column if not exists change_note text not null default '';

alter table public.dokohilf_guides
  drop constraint if exists dokohilf_guides_status_check;

update public.dokohilf_guides
set status = 'blocked'
where status = 'retired';

alter table public.dokohilf_guides
  add constraint dokohilf_guides_status_check
  check (status in ('draft', 'reviewed', 'approved', 'blocked'));

alter table public.dokohilf_guides
  drop constraint if exists dokohilf_guides_review_interval_days_check;

alter table public.dokohilf_guides
  add constraint dokohilf_guides_review_interval_days_check
  check (review_interval_days between 30 and 730);

update public.dokohilf_guides
set review_due_at = reviewed_at + make_interval(days => review_interval_days)
where reviewed_at is not null
  and review_due_at is null;

create table if not exists public.dokohilf_guide_versions (
  id bigint generated by default as identity primary key,
  guide_id uuid not null,
  slug text not null,
  title text not null,
  aliases text[] not null default '{}',
  steps jsonb not null default '[]'::jsonb,
  troubleshooting jsonb not null default '{}'::jsonb,
  status text not null,
  version integer not null,
  reviewed_at timestamptz,
  reviewed_role text,
  review_interval_days integer not null,
  review_due_at timestamptz,
  change_note text not null default '',
  changed_by uuid references auth.users(id) on delete set null,
  archived_at timestamptz not null default now()
);

create index if not exists dokohilf_guide_versions_guide_version_idx
  on public.dokohilf_guide_versions (guide_id, version desc, archived_at desc);

comment on table public.dokohilf_guide_versions is
  'Unveränderlicher Versionsverlauf redaktioneller DokoHilf-Anleitungen.';

create table if not exists public.dokohilf_editor_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('create', 'update', 'review', 'approve', 'block', 'role_check')),
  guide_id uuid,
  guide_slug text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.dokohilf_editor_audit is
  'Technischer Redaktionsnachweis ohne Gesprächs-, Bewohner- oder Gesundheitsdaten.';

create or replace function public.dokohilf_role_for(target_user uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select role
  from public.dokohilf_user_roles
  where user_id = target_user
    and active = true
  limit 1
$$;

create or replace function public.dokohilf_has_role(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(public.dokohilf_role_for(auth.uid()) = any(allowed_roles), false)
$$;

create or replace function public.dokohilf_can_write_guide_status(target_status text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select case public.dokohilf_role_for(auth.uid())
    when 'admin' then target_status in ('draft', 'reviewed', 'approved', 'blocked')
    when 'editor' then target_status in ('draft', 'reviewed')
    else false
  end
$$;

revoke all on function public.dokohilf_role_for(uuid) from public, anon;
revoke all on function public.dokohilf_has_role(text[]) from public, anon;
revoke all on function public.dokohilf_can_write_guide_status(text) from public, anon;
grant execute on function public.dokohilf_role_for(uuid) to authenticated, service_role;
grant execute on function public.dokohilf_has_role(text[]) to authenticated, service_role;
grant execute on function public.dokohilf_can_write_guide_status(text) to authenticated, service_role;

create or replace function public.dokohilf_archive_guide_version()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.dokohilf_guide_versions (
    guide_id, slug, title, aliases, steps, troubleshooting, status, version,
    reviewed_at, reviewed_role, review_interval_days, review_due_at,
    change_note, changed_by
  ) values (
    old.id, old.slug, old.title, old.aliases, old.steps, old.troubleshooting,
    old.status, old.version, old.reviewed_at, old.reviewed_role,
    old.review_interval_days, old.review_due_at, old.change_note, auth.uid()
  );

  if tg_op = 'DELETE' then
    return old;
  end if;

  if row(
    new.slug, new.title, new.aliases, new.steps, new.troubleshooting,
    new.status, new.review_interval_days
  ) is distinct from row(
    old.slug, old.title, old.aliases, old.steps, old.troubleshooting,
    old.status, old.review_interval_days
  ) then
    new.version := old.version + 1;
  end if;

  new.updated_at := now();

  if new.reviewed_at is distinct from old.reviewed_at
     or new.review_interval_days is distinct from old.review_interval_days then
    new.review_due_at := case
      when new.reviewed_at is null then null
      else new.reviewed_at + make_interval(days => new.review_interval_days)
    end;
  end if;

  if new.status = 'approved' and old.status is distinct from 'approved' then
    new.approved_at := now();
    new.approved_by := auth.uid();
  elsif new.status is distinct from 'approved' then
    new.approved_at := null;
    new.approved_by := null;
  end if;

  return new;
end
$$;

revoke all on function public.dokohilf_archive_guide_version() from public, anon, authenticated;

drop trigger if exists dokohilf_guides_archive_version on public.dokohilf_guides;
create trigger dokohilf_guides_archive_version
before update or delete on public.dokohilf_guides
for each row execute function public.dokohilf_archive_guide_version();

create or replace view public.dokohilf_editor_guides
with (security_invoker = true)
as
select
  g.*,
  (g.review_due_at is not null and g.review_due_at < now()) as is_overdue
from public.dokohilf_guides g;

alter table public.dokohilf_user_roles enable row level security;
alter table public.dokohilf_guides enable row level security;
alter table public.dokohilf_guide_versions enable row level security;
alter table public.dokohilf_editor_audit enable row level security;

revoke all on table public.dokohilf_user_roles from anon, authenticated;
revoke all on table public.dokohilf_guides from anon, authenticated;
revoke all on table public.dokohilf_guide_versions from anon, authenticated;
revoke all on table public.dokohilf_editor_audit from anon, authenticated;
revoke all on table public.dokohilf_editor_guides from anon, authenticated;

grant select on table public.dokohilf_user_roles to authenticated;
grant select, insert, update, delete on table public.dokohilf_guides to authenticated;
grant select on table public.dokohilf_guide_versions to authenticated;
grant select on table public.dokohilf_editor_guides to authenticated;

drop policy if exists dokohilf_roles_select_authorized on public.dokohilf_user_roles;
create policy dokohilf_roles_select_authorized
on public.dokohilf_user_roles
for select to authenticated
using (
  user_id = auth.uid()
  or public.dokohilf_has_role(array['admin'])
);

drop policy if exists dokohilf_guides_deny_anon on public.dokohilf_guides;
drop policy if exists dokohilf_guides_deny_authenticated on public.dokohilf_guides;
drop policy if exists dokohilf_guides_select_editor on public.dokohilf_guides;
drop policy if exists dokohilf_guides_insert_editor on public.dokohilf_guides;
drop policy if exists dokohilf_guides_update_editor on public.dokohilf_guides;
drop policy if exists dokohilf_guides_delete_admin on public.dokohilf_guides;

create policy dokohilf_guides_select_editor
on public.dokohilf_guides
for select to authenticated
using (public.dokohilf_has_role(array['editor', 'admin']));

create policy dokohilf_guides_insert_editor
on public.dokohilf_guides
for insert to authenticated
with check (public.dokohilf_can_write_guide_status(status));

create policy dokohilf_guides_update_editor
on public.dokohilf_guides
for update to authenticated
using (public.dokohilf_has_role(array['editor', 'admin']))
with check (public.dokohilf_can_write_guide_status(status));

create policy dokohilf_guides_delete_admin
on public.dokohilf_guides
for delete to authenticated
using (public.dokohilf_has_role(array['admin']));

drop policy if exists dokohilf_guide_versions_select_editor on public.dokohilf_guide_versions;
create policy dokohilf_guide_versions_select_editor
on public.dokohilf_guide_versions
for select to authenticated
using (public.dokohilf_has_role(array['editor', 'admin']));

-- Keine Client-Schreibrechte auf Rollen, Verlauf oder Audit. Änderungen laufen nur
-- kontrolliert über die JWT-geschützte Editor-Funktion beziehungsweise Administration.

create or replace function public.dokohilf_reject_public_signup(event jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(event->>'authentication_method', '') = 'invite' then
    return '{}'::jsonb;
  end if;

  return jsonb_build_object(
    'error', jsonb_build_object(
      'http_code', 403,
      'message', 'DokoHilf-Konten werden ausschließlich durch Einladung angelegt.'
    )
  );
end
$$;

grant usage on schema public to supabase_auth_admin;
grant execute on function public.dokohilf_reject_public_signup(jsonb) to supabase_auth_admin;
revoke execute on function public.dokohilf_reject_public_signup(jsonb) from public, anon, authenticated;

comment on function public.dokohilf_reject_public_signup(jsonb) is
  'Für den Supabase Before User Created Hook vorbereitet. Vor realem Rollout im Auth-Dashboard aktivieren.';
